name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - 'master'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: baseImagePath
    value: 'eu.gcr.io/'
  - name: imageName
    value: 'prod-bip/ssb/klass/subsets-webview'
  - name: snykServiceConnection
    value: 'Klass-Snyk'
  - name: snykOrganisation
    value: 'klass'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.42
      endpoint: statisticsnorway

jobs:
  - job: buildTestAndRunTest
    displayName: 'Test/build app and Dockerimage'
    steps:
      - template: 'docker/docker-build-snykscan-and-push-to-gcr.yaml@templates'
        parameters:
          imageName: $(imageName)
          snykServiceConnection: $(snykServiceConnection)
          snykOrganisation: $(snykOrganisation)
  - template: 'docker/docker-tag-for-production.yml@templates'
    parameters:
      tagToTag: 'master-$(fullSha)'
      gcrImageName: '$(baseImagePath)$(imageName)'
